[package]
name = "chatapp-rust"
version = "0.1.0"
authors = ["Oliver Kogel <kogel.oliver@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
