on:
  pull_request:
    branches:
      - main
name: TOC Generator
jobs:
  generateTOC:
    runs-on: ubuntu-latest
    steps:
    - uses: technote-space/toc-generator@v4.1.2
      with:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TOC_TITLE: "**Inhaltsverzeichnis**"
        # Git commit name.
        COMMIT_NAME: "TOCGEN"
        CREATE_PR: false
        TARGET_PATHS: "./[A-Z]*[A-Z]-[A-Z]*[A-Z]/README.md"
